name: Node.js Environment Variables

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test  # Specify the environment here
    env:
          TEST: ${{ vars.TEST }}
          SECRET: ${{ secrets.TEST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk   

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: ap-south-1


      - name: Run Node.js script to print environment variables
        run: node a.js

      - name: Synthesize CDK
        run: cdk synth